SAMPLE_RESTAURANTS = [
    {
        "name": "Trattoria Bella",
        "address": "ul. Wrocławska 18, Poznań",
        "description": "Domowy makaron, pizza na cienkim cieście i klasyczne włoskie desery.",
        "latitude": "52.407876",
        "longitude": "16.929423",
        "average_rating": "4.8",
        "review_count": 184,
        "cuisines": ["Włoska"],
    },
    {
        "name": "Ramen Nori",
        "address": "ul. Taczaka 10, Poznań",
        "description": "Ramen gotowany od podstaw, azjatyckie przystawki i sezonowe menu.",
        "latitude": "52.406434",
        "longitude": "16.920563",
        "average_rating": "4.7",
        "review_count": 231,
        "cuisines": ["Japońska"],
    },
    {
        "name": "Pyra i Spółka",
        "address": "ul. Ratajczaka 35, Poznań",
        "description": "Nowoczesne dania inspirowane kuchnią wielkopolską.",
        "latitude": "52.404820",
        "longitude": "16.921892",
        "average_rating": "4.4",
        "review_count": 96,
        "cuisines": ["Polska"],
    },
    {
        "name": "Masala House",
        "address": "ul. Półwiejska 42, Poznań",
        "description": "Aromatyczne curry, wypiekane naan i opcje wegetariańskie.",
        "latitude": "52.403652",
        "longitude": "16.925771",
        "average_rating": "4.6",
        "review_count": 147,
        "cuisines": ["Indyjska"],
    },
    {
        "name": "Verde Bistro",
        "address": "ul. Kwiatowa 14, Poznań",
        "description": "Sezonowe roślinne dania, śniadania i desery bez mięsa.",
        "latitude": "52.403051",
        "longitude": "16.925073",
        "average_rating": "4.2",
        "review_count": 73,
        "cuisines": ["Wegetariańska"],
    },
    {
        "name": "Casa Picante",
        "address": "ul. Żydowska 9, Poznań",
        "description": "Tacos, burrito i ostre sosy przygotowywane na miejscu.",
        "latitude": "52.409725",
        "longitude": "16.934671",
        "average_rating": "4.5",
        "review_count": 121,
        "cuisines": ["Meksykańska"],
    },
    {
        "name": "Złota Kaczka",
        "address": "ul. Garbary 61, Poznań",
        "description": "Kuchnia polska w bardziej eleganckim wydaniu.",
        "latitude": "52.410993",
        "longitude": "16.939152",
        "average_rating": "4.0",
        "review_count": 52,
        "cuisines": ["Polska"],
    },
    {
        "name": "Olive & Thyme",
        "address": "ul. Strzelecka 27, Poznań",
        "description": "Dania z oliwą, świeżymi warzywami i rybami.",
        "latitude": "52.405175",
        "longitude": "16.928743",
        "average_rating": "4.3",
        "review_count": 88,
        "cuisines": ["Śródziemnomorska"],
    },
]
